# Generated by Django 4.2.5 on 2023-09-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('dn', 'Completo'), ('ic', 'Incompleto'), ('ip', 'Em Andamento')], max_length=2)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
